---
# Ansible VSTS project variables
vsts_poolname: "FinProd-PRD-CE-Infra-Linux"
vsts_remove: false # Use true to uninstall
vsts_reinstall: false # Use true to reinstall
vsts_agent_user: "vstsuser"

# Linux terraform Variables
terraform_version: 0.11.13

# Docker Variables
docker_version: '18.06.1~ce~3-0~ubuntu'
docker_apt_release_channel: 'stable'
docker_apt_repository: 'deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}'
docker_group_members: 
  - 'vstsuser'

# Dotnet variables
dotnet_package: "dotnet-sdk-2.1.105"
dotnet_debian_repo_gpg_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
microsoft_xenial_ubuntu_repo: "https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod"
microsoft_bionic_ubuntu_repo: "https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod"

# Kubectl variables
kube_url_apt_key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
kube_url_apt: "https://apt.kubernetes.io/"
kube_source_list_file: "/etc/apt/sources.list.d/kubernetes.list"