---
### Ansible Taks for Windows System
  - name: Run ansible tasks on Windows
    hosts: windows
    tasks:

  ## VSTS Agent installation task    
      - name: install vsts agent
        include_role:
          name: stone-payments.win-vsts-agent
        vars: 
          vsts_agent_name: "{{ ansible_hostname }}-a{{ item }}"
          vsts_agentfolder: "C:\\vstsagent\\{{ vsts_agent_user }}\\a{{ item }}"
        loop: "{{ range(1,4) | list }}"  

  ## IIS installation tasks
      - name: Install IIS Features
        win_feature:
          name: "{{ item }}"
          include_sub_features: true 
          include_management_tools: true
          state: present
        with_items:
          - NET-Framework-45-Core        
          - Web-Asp-Net45
          - Web-Http-Errors
          - Web-Common-Http        
          - Web-Static-Content
          - NET-HTTP-Activation
          - NET-Non-HTTP-Activ
        register: win_iis_basic_features
        tags: iis_basic_features
        when: install_iis == true

      - name: Install IIS WCF Features
        win_feature:
          name: "{{ item }}"
          include_sub_features: true 
          include_management_tools: true
          state: present
        with_items:
          - NET-WCF-TCP-Activation45
          - NET-WCF-HTTP-Activation45
        register: win_iis_wcf_features
        tags: iis_wcf_features 
        when: install_wcf == true # Default value is false

  ## Dotnet core installation task
      - name: Install dotnet core
        win_chocolatey:
          name: "{{ dotnetcore_version }}"
          state: present
        register: win_dotnetcore
        tags: dotnetcore
        when: install_dotnetcore == true  # Default value is false

  ## Dotnet ful framework installation task
      - name: Install dotnet full
        win_chocolatey:
          name: "{{ dotnetfull_version }}"
          state: present
        register: win_dotnetfull
        tags: dotnetfull
        when: install_dotnetfull == true # Default value is false

  ## NSSM installation task
      - name: Install NSSM
        win_chocolatey:
          name: "{{ nssm_version }}"
          state: present
        register: win_nssm
        tags: nssm
        when: install_nssm == true # Default value is false