---
# Ansible VSTS project variables
vsts_poolname: "FinProd-PRD-EC2-Infra-Linux"
vsts_remove: false # Use true to uninstall
vsts_reinstall: false # Use true to reinstall
vsts_agent_user: "vstsuser"

# Linux terraform Variables
terraform_version: 0.11.13

ping_var: ola